import Link from 'next/link';
import ClientHeader from '../components/client-header';
import RegisterSW from '../components/register-sw';
import ServerHeader from '../components/server-header';
import { getAuthenticatedAppForUser } from '../lib/firebase/serverApp';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const { currentUser } = await getAuthenticatedAppForUser('LAYOUT');
	console.log('LAYOUT: currentUser', currentUser?.uid);

	return (
		<html lang="en">
			<body>
				<h1>LAYOUT</h1>
				<div className="flex">
					<Link style={{ margin: '8px' }} href="/">
						Home
					</Link>
					<Link style={{ margin: '8px' }} href="/clnt">
						Client page
					</Link>
					<Link style={{ margin: '8px' }} href="/srvr">
						Server page
					</Link>
				</div>
				{/* REGISTER THE SERVICE WORKER FOR ALL COMPONENT WHICH USE THIS LAYOUT */}
				<RegisterSW />
				<ServerHeader />
				<ClientHeader />
				{children}
			</body>
		</html>
	);
}
